export const EMPLOYEE_DOCUMENT_TYPES = [
  "Employee Application Form",
  "CV / Resume",
  "Recent Photograph",
  "CNIC / National ID Copy",
  "Passport Copy — if applicable",
  "Educational Certificates",
  "Educational Transcripts / Mark Sheets",
  "Experience Certificates",
  "Previous Employment / Relieving Letter",
  "Reference / Recommendation Letters",
  "Employee Information Form",
  "Employment / Appointment Letter",
  "Job Description",
  "Offer Letter",
  "Employment Contract / Agreement",
  "NDA — Non-Disclosure Agreement",
  "Company Policies Acknowledgment",
  "Code of Conduct Agreement",
  "IT / Computer Usage Policy Acknowledgment",
  "Data Privacy / Confidentiality Agreement",
  "Bank Account / Salary Details",
  "Tax Information / Tax Documents",
  "Emergency Contact Form",
  "Medical / Fitness Certificate — if required",
  "Background Verification Report — if applicable",
  "Police / Character Certificate — if required",
  "Joining / Onboarding Checklist",
  "Employee ID Card Record",
  "Asset Handover Form",
  "Laptop / Computer Handover Form",
  "SIM / Mobile / Other Equipment Handover",
  "Leave Records",
  "Attendance Records",
  "Performance Evaluation Records",
  "Training / Certification Records",
  "Warning / Disciplinary Records — if applicable",
  "Promotion / Salary Revision Letters",
  "Transfer / Department Change Records",
  "Increment Letter",
  "Resignation Letter",
  "Exit Interview Form",
  "Clearance Form",
  "Final Settlement Record",
  "Experience / Service Certificate",
  "Relieving Letter",
  "Company Asset Return Form",
  "Employee File Closing Checklist",
];

export const EMPLOYEE_DOCUMENT_TYPE_OPTIONS = EMPLOYEE_DOCUMENT_TYPES.map((docType) => ({
  value: docType,
  label: docType,
}));