/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'
import { Route as AppAutoVerifiedRouteImport } from './routes/_app.auto-verified'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppInboxRouteImport } from './routes/_app.inbox'
import { Route as AppLeavesRouteImport } from './routes/_app.leaves'
import { Route as AppMyAssetsRouteImport } from './routes/_app.my-assets'
import { Route as AppMyExpensesRouteImport } from './routes/_app.my-expenses'
import { Route as AppMyLettersRouteImport } from './routes/_app.my-letters'
import { Route as AppMyResignationRouteImport } from './routes/_app.my-resignation'
import { Route as AppPaymentsRouteImport } from './routes/_app.payments'
import { Route as AppPayrollRouteImport } from './routes/_app.payroll'
import { Route as AppRequestsRouteImport } from './routes/_app.requests'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as SystemAdminForgotPasswordRouteImport } from './routes/system-admin.forgot-password'
import { Route as SystemAdminLoginRouteImport } from './routes/system-admin.login'
import { Route as SystemAdminResetPasswordRouteImport } from './routes/system-admin.reset-password'
import { Route as VerifyQrTokenRouteImport } from './routes/verify.$qrToken'
import { Route as AppAdminActivityLogsRouteImport } from './routes/_app.admin.activity-logs'
import { Route as AppAdminLeadsRouteImport } from './routes/_app.admin.leads'
import { Route as AppAdminLoginHistoryRouteImport } from './routes/_app.admin.login-history'
import { Route as AppAdminNullRequestsRouteImport } from './routes/_app.admin.null-requests'
import { Route as AppAdminOrganizationsRouteImport } from './routes/_app.admin.organizations'
import { Route as AppAdminPaymentsRouteImport } from './routes/_app.admin.payments'
import { Route as AppAdminRequestsRouteImport } from './routes/_app.admin.requests'
import { Route as AppAdminSupportRouteImport } from './routes/_app.admin.support'
import { Route as AppAdminUnresponsiveRouteImport } from './routes/_app.admin.unresponsive'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'
import { Route as AppAutoVerifiedUuidRouteImport } from './routes/_app.auto-verified_.$uuid'
import { Route as AppOrgAdminsRouteImport } from './routes/_app.org.admins'
import { Route as AppOrgAssetCategoriesRouteImport } from './routes/_app.org.asset-categories'
import { Route as AppOrgAssetsRouteImport } from './routes/_app.org.assets'
import { Route as AppOrgAttendanceRouteImport } from './routes/_app.org.attendance'
import { Route as AppOrgExpenseClaimsRouteImport } from './routes/_app.org.expense-claims'
import { Route as AppOrgHrLettersRouteImport } from './routes/_app.org.hr-letters'
import { Route as AppOrgLeavesRouteImport } from './routes/_app.org.leaves'
import { Route as AppOrgLetterTemplatesRouteImport } from './routes/_app.org.letter-templates'
import { Route as AppOrgOffboardingRouteImport } from './routes/_app.org.offboarding'
import { Route as AppOrgPayrollRouteImport } from './routes/_app.org.payroll'
import { Route as AppOrgSalaryComponentsRouteImport } from './routes/_app.org.salary-components'
import { Route as AppOrgSupportRouteImport } from './routes/_app.org.support'
import { Route as AppOrgTeamRouteImport } from './routes/_app.org.team'
import { Route as AppPaymentCallbackRouteImport } from './routes/_app.payment.callback'
import { Route as VerifyLetterQrTokenRouteImport } from './routes/verify.letter.$qrToken'
import { Route as AppAdminSupportIndexRouteImport } from './routes/_app.admin.support.index'
import { Route as AppAdminSupportUuidRouteImport } from './routes/_app.admin.support.$uuid'
import { Route as AppOrgSupportIndexRouteImport } from './routes/_app.org.support.index'
import { Route as AppOrgSupportUuidRouteImport } from './routes/_app.org.support.$uuid'
import { Route as AppOrgTeamIndexRouteImport } from './routes/_app.org.team.index'
import { Route as AppOrgTeamUuidRouteImport } from './routes/_app.org.team.$uuid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAutoVerifiedRoute = AppAutoVerifiedRouteImport.update({
  id: '/auto-verified',
  path: '/auto-verified',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppLeavesRoute = AppLeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => AppRoute,
} as any)
const AppMyAssetsRoute = AppMyAssetsRouteImport.update({
  id: '/my-assets',
  path: '/my-assets',
  getParentRoute: () => AppRoute,
} as any)
const AppMyExpensesRoute = AppMyExpensesRouteImport.update({
  id: '/my-expenses',
  path: '/my-expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppMyLettersRoute = AppMyLettersRouteImport.update({
  id: '/my-letters',
  path: '/my-letters',
  getParentRoute: () => AppRoute,
} as any)
const AppMyResignationRoute = AppMyResignationRouteImport.update({
  id: '/my-resignation',
  path: '/my-resignation',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRoute = AppPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsRoute = AppRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const SystemAdminForgotPasswordRoute =
  SystemAdminForgotPasswordRouteImport.update({
    id: '/system-admin/forgot-password',
    path: '/system-admin/forgot-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const SystemAdminLoginRoute = SystemAdminLoginRouteImport.update({
  id: '/system-admin/login',
  path: '/system-admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemAdminResetPasswordRoute =
  SystemAdminResetPasswordRouteImport.update({
    id: '/system-admin/reset-password',
    path: '/system-admin/reset-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const VerifyQrTokenRoute = VerifyQrTokenRouteImport.update({
  id: '/verify/$qrToken',
  path: '/verify/$qrToken',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminActivityLogsRoute = AppAdminActivityLogsRouteImport.update({
  id: '/admin/activity-logs',
  path: '/admin/activity-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminLeadsRoute = AppAdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminLoginHistoryRoute = AppAdminLoginHistoryRouteImport.update({
  id: '/admin/login-history',
  path: '/admin/login-history',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminNullRequestsRoute = AppAdminNullRequestsRouteImport.update({
  id: '/admin/null-requests',
  path: '/admin/null-requests',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminOrganizationsRoute = AppAdminOrganizationsRouteImport.update({
  id: '/admin/organizations',
  path: '/admin/organizations',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPaymentsRoute = AppAdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRequestsRoute = AppAdminRequestsRouteImport.update({
  id: '/admin/requests',
  path: '/admin/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSupportRoute = AppAdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUnresponsiveRoute = AppAdminUnresponsiveRouteImport.update({
  id: '/admin/unresponsive',
  path: '/admin/unresponsive',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAutoVerifiedUuidRoute = AppAutoVerifiedUuidRouteImport.update({
  id: '/auto-verified_/$uuid',
  path: '/auto-verified/$uuid',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgAdminsRoute = AppOrgAdminsRouteImport.update({
  id: '/org/admins',
  path: '/org/admins',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgAssetCategoriesRoute = AppOrgAssetCategoriesRouteImport.update({
  id: '/org/asset-categories',
  path: '/org/asset-categories',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgAssetsRoute = AppOrgAssetsRouteImport.update({
  id: '/org/assets',
  path: '/org/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgAttendanceRoute = AppOrgAttendanceRouteImport.update({
  id: '/org/attendance',
  path: '/org/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgExpenseClaimsRoute = AppOrgExpenseClaimsRouteImport.update({
  id: '/org/expense-claims',
  path: '/org/expense-claims',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgHrLettersRoute = AppOrgHrLettersRouteImport.update({
  id: '/org/hr-letters',
  path: '/org/hr-letters',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgLeavesRoute = AppOrgLeavesRouteImport.update({
  id: '/org/leaves',
  path: '/org/leaves',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgLetterTemplatesRoute = AppOrgLetterTemplatesRouteImport.update({
  id: '/org/letter-templates',
  path: '/org/letter-templates',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgOffboardingRoute = AppOrgOffboardingRouteImport.update({
  id: '/org/offboarding',
  path: '/org/offboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgPayrollRoute = AppOrgPayrollRouteImport.update({
  id: '/org/payroll',
  path: '/org/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgSalaryComponentsRoute = AppOrgSalaryComponentsRouteImport.update({
  id: '/org/salary-components',
  path: '/org/salary-components',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgSupportRoute = AppOrgSupportRouteImport.update({
  id: '/org/support',
  path: '/org/support',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgTeamRoute = AppOrgTeamRouteImport.update({
  id: '/org/team',
  path: '/org/team',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentCallbackRoute = AppPaymentCallbackRouteImport.update({
  id: '/payment/callback',
  path: '/payment/callback',
  getParentRoute: () => AppRoute,
} as any)
const VerifyLetterQrTokenRoute = VerifyLetterQrTokenRouteImport.update({
  id: '/verify/letter/$qrToken',
  path: '/verify/letter/$qrToken',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminSupportIndexRoute = AppAdminSupportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminSupportRoute,
} as any)
const AppAdminSupportUuidRoute = AppAdminSupportUuidRouteImport.update({
  id: '/$uuid',
  path: '/$uuid',
  getParentRoute: () => AppAdminSupportRoute,
} as any)
const AppOrgSupportIndexRoute = AppOrgSupportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgSupportRoute,
} as any)
const AppOrgSupportUuidRoute = AppOrgSupportUuidRouteImport.update({
  id: '/$uuid',
  path: '/$uuid',
  getParentRoute: () => AppOrgSupportRoute,
} as any)
const AppOrgTeamIndexRoute = AppOrgTeamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgTeamRoute,
} as any)
const AppOrgTeamUuidRoute = AppOrgTeamUuidRouteImport.update({
  id: '/$uuid',
  path: '/$uuid',
  getParentRoute: () => AppOrgTeamRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/attendance': typeof AppAttendanceRoute
  '/auto-verified': typeof AppAutoVerifiedRoute
  '/dashboard': typeof AppDashboardRoute
  '/inbox': typeof AppInboxRoute
  '/leaves': typeof AppLeavesRoute
  '/my-assets': typeof AppMyAssetsRoute
  '/my-expenses': typeof AppMyExpensesRoute
  '/my-letters': typeof AppMyLettersRoute
  '/my-resignation': typeof AppMyResignationRoute
  '/payments': typeof AppPaymentsRoute
  '/payroll': typeof AppPayrollRoute
  '/requests': typeof AppRequestsRoute
  '/settings': typeof AppSettingsRoute
  '/system-admin/forgot-password': typeof SystemAdminForgotPasswordRoute
  '/system-admin/login': typeof SystemAdminLoginRoute
  '/system-admin/reset-password': typeof SystemAdminResetPasswordRoute
  '/verify/$qrToken': typeof VerifyQrTokenRoute
  '/admin/activity-logs': typeof AppAdminActivityLogsRoute
  '/admin/leads': typeof AppAdminLeadsRoute
  '/admin/login-history': typeof AppAdminLoginHistoryRoute
  '/admin/null-requests': typeof AppAdminNullRequestsRoute
  '/admin/organizations': typeof AppAdminOrganizationsRoute
  '/admin/payments': typeof AppAdminPaymentsRoute
  '/admin/requests': typeof AppAdminRequestsRoute
  '/admin/support': typeof AppAdminSupportRouteWithChildren
  '/admin/unresponsive': typeof AppAdminUnresponsiveRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/auto-verified/$uuid': typeof AppAutoVerifiedUuidRoute
  '/org/admins': typeof AppOrgAdminsRoute
  '/org/asset-categories': typeof AppOrgAssetCategoriesRoute
  '/org/assets': typeof AppOrgAssetsRoute
  '/org/attendance': typeof AppOrgAttendanceRoute
  '/org/expense-claims': typeof AppOrgExpenseClaimsRoute
  '/org/hr-letters': typeof AppOrgHrLettersRoute
  '/org/leaves': typeof AppOrgLeavesRoute
  '/org/letter-templates': typeof AppOrgLetterTemplatesRoute
  '/org/offboarding': typeof AppOrgOffboardingRoute
  '/org/payroll': typeof AppOrgPayrollRoute
  '/org/salary-components': typeof AppOrgSalaryComponentsRoute
  '/org/support': typeof AppOrgSupportRouteWithChildren
  '/org/team': typeof AppOrgTeamRouteWithChildren
  '/payment/callback': typeof AppPaymentCallbackRoute
  '/verify/letter/$qrToken': typeof VerifyLetterQrTokenRoute
  '/admin/support/$uuid': typeof AppAdminSupportUuidRoute
  '/org/support/$uuid': typeof AppOrgSupportUuidRoute
  '/org/team/$uuid': typeof AppOrgTeamUuidRoute
  '/admin/support/': typeof AppAdminSupportIndexRoute
  '/org/support/': typeof AppOrgSupportIndexRoute
  '/org/team/': typeof AppOrgTeamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/attendance': typeof AppAttendanceRoute
  '/auto-verified': typeof AppAutoVerifiedRoute
  '/dashboard': typeof AppDashboardRoute
  '/inbox': typeof AppInboxRoute
  '/leaves': typeof AppLeavesRoute
  '/my-assets': typeof AppMyAssetsRoute
  '/my-expenses': typeof AppMyExpensesRoute
  '/my-letters': typeof AppMyLettersRoute
  '/my-resignation': typeof AppMyResignationRoute
  '/payments': typeof AppPaymentsRoute
  '/payroll': typeof AppPayrollRoute
  '/requests': typeof AppRequestsRoute
  '/settings': typeof AppSettingsRoute
  '/system-admin/forgot-password': typeof SystemAdminForgotPasswordRoute
  '/system-admin/login': typeof SystemAdminLoginRoute
  '/system-admin/reset-password': typeof SystemAdminResetPasswordRoute
  '/verify/$qrToken': typeof VerifyQrTokenRoute
  '/admin/activity-logs': typeof AppAdminActivityLogsRoute
  '/admin/leads': typeof AppAdminLeadsRoute
  '/admin/login-history': typeof AppAdminLoginHistoryRoute
  '/admin/null-requests': typeof AppAdminNullRequestsRoute
  '/admin/organizations': typeof AppAdminOrganizationsRoute
  '/admin/payments': typeof AppAdminPaymentsRoute
  '/admin/requests': typeof AppAdminRequestsRoute
  '/admin/unresponsive': typeof AppAdminUnresponsiveRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/auto-verified/$uuid': typeof AppAutoVerifiedUuidRoute
  '/org/admins': typeof AppOrgAdminsRoute
  '/org/asset-categories': typeof AppOrgAssetCategoriesRoute
  '/org/assets': typeof AppOrgAssetsRoute
  '/org/attendance': typeof AppOrgAttendanceRoute
  '/org/expense-claims': typeof AppOrgExpenseClaimsRoute
  '/org/hr-letters': typeof AppOrgHrLettersRoute
  '/org/leaves': typeof AppOrgLeavesRoute
  '/org/letter-templates': typeof AppOrgLetterTemplatesRoute
  '/org/offboarding': typeof AppOrgOffboardingRoute
  '/org/payroll': typeof AppOrgPayrollRoute
  '/org/salary-components': typeof AppOrgSalaryComponentsRoute
  '/payment/callback': typeof AppPaymentCallbackRoute
  '/verify/letter/$qrToken': typeof VerifyLetterQrTokenRoute
  '/admin/support/$uuid': typeof AppAdminSupportUuidRoute
  '/org/support/$uuid': typeof AppOrgSupportUuidRoute
  '/org/team/$uuid': typeof AppOrgTeamUuidRoute
  '/admin/support': typeof AppAdminSupportIndexRoute
  '/org/support': typeof AppOrgSupportIndexRoute
  '/org/team': typeof AppOrgTeamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/auto-verified': typeof AppAutoVerifiedRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/leaves': typeof AppLeavesRoute
  '/_app/my-assets': typeof AppMyAssetsRoute
  '/_app/my-expenses': typeof AppMyExpensesRoute
  '/_app/my-letters': typeof AppMyLettersRoute
  '/_app/my-resignation': typeof AppMyResignationRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/payroll': typeof AppPayrollRoute
  '/_app/requests': typeof AppRequestsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/system-admin/forgot-password': typeof SystemAdminForgotPasswordRoute
  '/system-admin/login': typeof SystemAdminLoginRoute
  '/system-admin/reset-password': typeof SystemAdminResetPasswordRoute
  '/verify/$qrToken': typeof VerifyQrTokenRoute
  '/_app/admin/activity-logs': typeof AppAdminActivityLogsRoute
  '/_app/admin/leads': typeof AppAdminLeadsRoute
  '/_app/admin/login-history': typeof AppAdminLoginHistoryRoute
  '/_app/admin/null-requests': typeof AppAdminNullRequestsRoute
  '/_app/admin/organizations': typeof AppAdminOrganizationsRoute
  '/_app/admin/payments': typeof AppAdminPaymentsRoute
  '/_app/admin/requests': typeof AppAdminRequestsRoute
  '/_app/admin/support': typeof AppAdminSupportRouteWithChildren
  '/_app/admin/unresponsive': typeof AppAdminUnresponsiveRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/auto-verified_/$uuid': typeof AppAutoVerifiedUuidRoute
  '/_app/org/admins': typeof AppOrgAdminsRoute
  '/_app/org/asset-categories': typeof AppOrgAssetCategoriesRoute
  '/_app/org/assets': typeof AppOrgAssetsRoute
  '/_app/org/attendance': typeof AppOrgAttendanceRoute
  '/_app/org/expense-claims': typeof AppOrgExpenseClaimsRoute
  '/_app/org/hr-letters': typeof AppOrgHrLettersRoute
  '/_app/org/leaves': typeof AppOrgLeavesRoute
  '/_app/org/letter-templates': typeof AppOrgLetterTemplatesRoute
  '/_app/org/offboarding': typeof AppOrgOffboardingRoute
  '/_app/org/payroll': typeof AppOrgPayrollRoute
  '/_app/org/salary-components': typeof AppOrgSalaryComponentsRoute
  '/_app/org/support': typeof AppOrgSupportRouteWithChildren
  '/_app/org/team': typeof AppOrgTeamRouteWithChildren
  '/_app/payment/callback': typeof AppPaymentCallbackRoute
  '/verify/letter/$qrToken': typeof VerifyLetterQrTokenRoute
  '/_app/admin/support/$uuid': typeof AppAdminSupportUuidRoute
  '/_app/org/support/$uuid': typeof AppOrgSupportUuidRoute
  '/_app/org/team/$uuid': typeof AppOrgTeamUuidRoute
  '/_app/admin/support/': typeof AppAdminSupportIndexRoute
  '/_app/org/support/': typeof AppOrgSupportIndexRoute
  '/_app/org/team/': typeof AppOrgTeamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/set-password'
    | '/attendance'
    | '/auto-verified'
    | '/dashboard'
    | '/inbox'
    | '/leaves'
    | '/my-assets'
    | '/my-expenses'
    | '/my-letters'
    | '/my-resignation'
    | '/payments'
    | '/payroll'
    | '/requests'
    | '/settings'
    | '/system-admin/forgot-password'
    | '/system-admin/login'
    | '/system-admin/reset-password'
    | '/verify/$qrToken'
    | '/admin/activity-logs'
    | '/admin/leads'
    | '/admin/login-history'
    | '/admin/null-requests'
    | '/admin/organizations'
    | '/admin/payments'
    | '/admin/requests'
    | '/admin/support'
    | '/admin/unresponsive'
    | '/admin/users'
    | '/auto-verified/$uuid'
    | '/org/admins'
    | '/org/asset-categories'
    | '/org/assets'
    | '/org/attendance'
    | '/org/expense-claims'
    | '/org/hr-letters'
    | '/org/leaves'
    | '/org/letter-templates'
    | '/org/offboarding'
    | '/org/payroll'
    | '/org/salary-components'
    | '/org/support'
    | '/org/team'
    | '/payment/callback'
    | '/verify/letter/$qrToken'
    | '/admin/support/$uuid'
    | '/org/support/$uuid'
    | '/org/team/$uuid'
    | '/admin/support/'
    | '/org/support/'
    | '/org/team/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/set-password'
    | '/attendance'
    | '/auto-verified'
    | '/dashboard'
    | '/inbox'
    | '/leaves'
    | '/my-assets'
    | '/my-expenses'
    | '/my-letters'
    | '/my-resignation'
    | '/payments'
    | '/payroll'
    | '/requests'
    | '/settings'
    | '/system-admin/forgot-password'
    | '/system-admin/login'
    | '/system-admin/reset-password'
    | '/verify/$qrToken'
    | '/admin/activity-logs'
    | '/admin/leads'
    | '/admin/login-history'
    | '/admin/null-requests'
    | '/admin/organizations'
    | '/admin/payments'
    | '/admin/requests'
    | '/admin/unresponsive'
    | '/admin/users'
    | '/auto-verified/$uuid'
    | '/org/admins'
    | '/org/asset-categories'
    | '/org/assets'
    | '/org/attendance'
    | '/org/expense-claims'
    | '/org/hr-letters'
    | '/org/leaves'
    | '/org/letter-templates'
    | '/org/offboarding'
    | '/org/payroll'
    | '/org/salary-components'
    | '/payment/callback'
    | '/verify/letter/$qrToken'
    | '/admin/support/$uuid'
    | '/org/support/$uuid'
    | '/org/team/$uuid'
    | '/admin/support'
    | '/org/support'
    | '/org/team'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/set-password'
    | '/_app/attendance'
    | '/_app/auto-verified'
    | '/_app/dashboard'
    | '/_app/inbox'
    | '/_app/leaves'
    | '/_app/my-assets'
    | '/_app/my-expenses'
    | '/_app/my-letters'
    | '/_app/my-resignation'
    | '/_app/payments'
    | '/_app/payroll'
    | '/_app/requests'
    | '/_app/settings'
    | '/system-admin/forgot-password'
    | '/system-admin/login'
    | '/system-admin/reset-password'
    | '/verify/$qrToken'
    | '/_app/admin/activity-logs'
    | '/_app/admin/leads'
    | '/_app/admin/login-history'
    | '/_app/admin/null-requests'
    | '/_app/admin/organizations'
    | '/_app/admin/payments'
    | '/_app/admin/requests'
    | '/_app/admin/support'
    | '/_app/admin/unresponsive'
    | '/_app/admin/users'
    | '/_app/auto-verified_/$uuid'
    | '/_app/org/admins'
    | '/_app/org/asset-categories'
    | '/_app/org/assets'
    | '/_app/org/attendance'
    | '/_app/org/expense-claims'
    | '/_app/org/hr-letters'
    | '/_app/org/leaves'
    | '/_app/org/letter-templates'
    | '/_app/org/offboarding'
    | '/_app/org/payroll'
    | '/_app/org/salary-components'
    | '/_app/org/support'
    | '/_app/org/team'
    | '/_app/payment/callback'
    | '/verify/letter/$qrToken'
    | '/_app/admin/support/$uuid'
    | '/_app/org/support/$uuid'
    | '/_app/org/team/$uuid'
    | '/_app/admin/support/'
    | '/_app/org/support/'
    | '/_app/org/team/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetPasswordRoute: typeof SetPasswordRoute
  SystemAdminForgotPasswordRoute: typeof SystemAdminForgotPasswordRoute
  SystemAdminLoginRoute: typeof SystemAdminLoginRoute
  SystemAdminResetPasswordRoute: typeof SystemAdminResetPasswordRoute
  VerifyQrTokenRoute: typeof VerifyQrTokenRoute
  VerifyLetterQrTokenRoute: typeof VerifyLetterQrTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auto-verified': {
      id: '/_app/auto-verified'
      path: '/auto-verified'
      fullPath: '/auto-verified'
      preLoaderRoute: typeof AppAutoVerifiedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaves': {
      id: '/_app/leaves'
      path: '/leaves'
      fullPath: '/leaves'
      preLoaderRoute: typeof AppLeavesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-assets': {
      id: '/_app/my-assets'
      path: '/my-assets'
      fullPath: '/my-assets'
      preLoaderRoute: typeof AppMyAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-expenses': {
      id: '/_app/my-expenses'
      path: '/my-expenses'
      fullPath: '/my-expenses'
      preLoaderRoute: typeof AppMyExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-letters': {
      id: '/_app/my-letters'
      path: '/my-letters'
      fullPath: '/my-letters'
      preLoaderRoute: typeof AppMyLettersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-resignation': {
      id: '/_app/my-resignation'
      path: '/my-resignation'
      fullPath: '/my-resignation'
      preLoaderRoute: typeof AppMyResignationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll': {
      id: '/_app/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AppPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/requests': {
      id: '/_app/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AppRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/system-admin/forgot-password': {
      id: '/system-admin/forgot-password'
      path: '/system-admin/forgot-password'
      fullPath: '/system-admin/forgot-password'
      preLoaderRoute: typeof SystemAdminForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-admin/login': {
      id: '/system-admin/login'
      path: '/system-admin/login'
      fullPath: '/system-admin/login'
      preLoaderRoute: typeof SystemAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-admin/reset-password': {
      id: '/system-admin/reset-password'
      path: '/system-admin/reset-password'
      fullPath: '/system-admin/reset-password'
      preLoaderRoute: typeof SystemAdminResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$qrToken': {
      id: '/verify/$qrToken'
      path: '/verify/$qrToken'
      fullPath: '/verify/$qrToken'
      preLoaderRoute: typeof VerifyQrTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/activity-logs': {
      id: '/_app/admin/activity-logs'
      path: '/admin/activity-logs'
      fullPath: '/admin/activity-logs'
      preLoaderRoute: typeof AppAdminActivityLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/leads': {
      id: '/_app/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AppAdminLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/login-history': {
      id: '/_app/admin/login-history'
      path: '/admin/login-history'
      fullPath: '/admin/login-history'
      preLoaderRoute: typeof AppAdminLoginHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/null-requests': {
      id: '/_app/admin/null-requests'
      path: '/admin/null-requests'
      fullPath: '/admin/null-requests'
      preLoaderRoute: typeof AppAdminNullRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/organizations': {
      id: '/_app/admin/organizations'
      path: '/admin/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AppAdminOrganizationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/payments': {
      id: '/_app/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AppAdminPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/requests': {
      id: '/_app/admin/requests'
      path: '/admin/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AppAdminRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/support': {
      id: '/_app/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AppAdminSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/unresponsive': {
      id: '/_app/admin/unresponsive'
      path: '/admin/unresponsive'
      fullPath: '/admin/unresponsive'
      preLoaderRoute: typeof AppAdminUnresponsiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auto-verified_/$uuid': {
      id: '/_app/auto-verified_/$uuid'
      path: '/auto-verified/$uuid'
      fullPath: '/auto-verified/$uuid'
      preLoaderRoute: typeof AppAutoVerifiedUuidRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/org/admins': {
      id: '/_app/org/admins'
      path: '/org/admins'
      fullPath: '/org/admins'
      preLoaderRoute: typeof AppOrgAdminsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/org/asset-categories': {
      id: '/_app/org/asset-categories'
      path: '/org/asset-categories'
      fullPath: '/org/asset-categories'
      preLoaderRoute: typeof AppOrgAssetCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/org/assets': {
      id: '/_app/org/assets'
      path: '/org/assets'
      fullPath: '/org/assets'
      preLoaderRoute: typeof AppOrgAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/org/attendance': {
      id: '/_app/org/attendance'
      path: '/org/attendance'
      fullPath: '/org/attendance'
      preLoaderRoute: typeof AppOrgAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/org/expense-claims': {
      id: '/_app/org/expense-claims'
      path: '/org/expense-claims'
      fullPath: '/org/expense-claims'
      preLoaderRoute: typeof AppOrgExpenseClaimsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/org/hr-letters': {
      id: '/_app/org/hr-letters'
      path: '/org/hr-letters'
      fullPath: '/org/hr-letters'
      preLoaderRoute: typeof AppOrgHrLettersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/org/leaves': {
      id: '/_app/org/leaves'
      path: '/org/leaves'
      fullPath: '/org/leaves'
      preLoaderRoute: typeof AppOrgLeavesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/org/letter-templates': {
      id: '/_app/org/letter-templates'
      path: '/org/letter-templates'
      fullPath: '/org/letter-templates'
      preLoaderRoute: typeof AppOrgLetterTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/org/offboarding': {
      id: '/_app/org/offboarding'
      path: '/org/offboarding'
      fullPath: '/org/offboarding'
      preLoaderRoute: typeof AppOrgOffboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/org/payroll': {
      id: '/_app/org/payroll'
      path: '/org/payroll'
      fullPath: '/org/payroll'
      preLoaderRoute: typeof AppOrgPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/org/salary-components': {
      id: '/_app/org/salary-components'
      path: '/org/salary-components'
      fullPath: '/org/salary-components'
      preLoaderRoute: typeof AppOrgSalaryComponentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/org/support': {
      id: '/_app/org/support'
      path: '/org/support'
      fullPath: '/org/support'
      preLoaderRoute: typeof AppOrgSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/org/team': {
      id: '/_app/org/team'
      path: '/org/team'
      fullPath: '/org/team'
      preLoaderRoute: typeof AppOrgTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payment/callback': {
      id: '/_app/payment/callback'
      path: '/payment/callback'
      fullPath: '/payment/callback'
      preLoaderRoute: typeof AppPaymentCallbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/verify/letter/$qrToken': {
      id: '/verify/letter/$qrToken'
      path: '/verify/letter/$qrToken'
      fullPath: '/verify/letter/$qrToken'
      preLoaderRoute: typeof VerifyLetterQrTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/support/': {
      id: '/_app/admin/support/'
      path: '/'
      fullPath: '/admin/support/'
      preLoaderRoute: typeof AppAdminSupportIndexRouteImport
      parentRoute: typeof AppAdminSupportRoute
    }
    '/_app/admin/support/$uuid': {
      id: '/_app/admin/support/$uuid'
      path: '/$uuid'
      fullPath: '/admin/support/$uuid'
      preLoaderRoute: typeof AppAdminSupportUuidRouteImport
      parentRoute: typeof AppAdminSupportRoute
    }
    '/_app/org/support/': {
      id: '/_app/org/support/'
      path: '/'
      fullPath: '/org/support/'
      preLoaderRoute: typeof AppOrgSupportIndexRouteImport
      parentRoute: typeof AppOrgSupportRoute
    }
    '/_app/org/support/$uuid': {
      id: '/_app/org/support/$uuid'
      path: '/$uuid'
      fullPath: '/org/support/$uuid'
      preLoaderRoute: typeof AppOrgSupportUuidRouteImport
      parentRoute: typeof AppOrgSupportRoute
    }
    '/_app/org/team/': {
      id: '/_app/org/team/'
      path: '/'
      fullPath: '/org/team/'
      preLoaderRoute: typeof AppOrgTeamIndexRouteImport
      parentRoute: typeof AppOrgTeamRoute
    }
    '/_app/org/team/$uuid': {
      id: '/_app/org/team/$uuid'
      path: '/$uuid'
      fullPath: '/org/team/$uuid'
      preLoaderRoute: typeof AppOrgTeamUuidRouteImport
      parentRoute: typeof AppOrgTeamRoute
    }
  }
}

interface AppAdminSupportRouteChildren {
  AppAdminSupportUuidRoute: typeof AppAdminSupportUuidRoute
  AppAdminSupportIndexRoute: typeof AppAdminSupportIndexRoute
}

const AppAdminSupportRouteChildren: AppAdminSupportRouteChildren = {
  AppAdminSupportUuidRoute: AppAdminSupportUuidRoute,
  AppAdminSupportIndexRoute: AppAdminSupportIndexRoute,
}

const AppAdminSupportRouteWithChildren = AppAdminSupportRoute._addFileChildren(
  AppAdminSupportRouteChildren,
)

interface AppOrgSupportRouteChildren {
  AppOrgSupportUuidRoute: typeof AppOrgSupportUuidRoute
  AppOrgSupportIndexRoute: typeof AppOrgSupportIndexRoute
}

const AppOrgSupportRouteChildren: AppOrgSupportRouteChildren = {
  AppOrgSupportUuidRoute: AppOrgSupportUuidRoute,
  AppOrgSupportIndexRoute: AppOrgSupportIndexRoute,
}

const AppOrgSupportRouteWithChildren = AppOrgSupportRoute._addFileChildren(
  AppOrgSupportRouteChildren,
)

interface AppOrgTeamRouteChildren {
  AppOrgTeamUuidRoute: typeof AppOrgTeamUuidRoute
  AppOrgTeamIndexRoute: typeof AppOrgTeamIndexRoute
}

const AppOrgTeamRouteChildren: AppOrgTeamRouteChildren = {
  AppOrgTeamUuidRoute: AppOrgTeamUuidRoute,
  AppOrgTeamIndexRoute: AppOrgTeamIndexRoute,
}

const AppOrgTeamRouteWithChildren = AppOrgTeamRoute._addFileChildren(
  AppOrgTeamRouteChildren,
)

interface AppRouteChildren {
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppAutoVerifiedRoute: typeof AppAutoVerifiedRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInboxRoute: typeof AppInboxRoute
  AppLeavesRoute: typeof AppLeavesRoute
  AppMyAssetsRoute: typeof AppMyAssetsRoute
  AppMyExpensesRoute: typeof AppMyExpensesRoute
  AppMyLettersRoute: typeof AppMyLettersRoute
  AppMyResignationRoute: typeof AppMyResignationRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppPayrollRoute: typeof AppPayrollRoute
  AppRequestsRoute: typeof AppRequestsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppAdminActivityLogsRoute: typeof AppAdminActivityLogsRoute
  AppAdminLeadsRoute: typeof AppAdminLeadsRoute
  AppAdminLoginHistoryRoute: typeof AppAdminLoginHistoryRoute
  AppAdminNullRequestsRoute: typeof AppAdminNullRequestsRoute
  AppAdminOrganizationsRoute: typeof AppAdminOrganizationsRoute
  AppAdminPaymentsRoute: typeof AppAdminPaymentsRoute
  AppAdminRequestsRoute: typeof AppAdminRequestsRoute
  AppAdminSupportRoute: typeof AppAdminSupportRouteWithChildren
  AppAdminUnresponsiveRoute: typeof AppAdminUnresponsiveRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAutoVerifiedUuidRoute: typeof AppAutoVerifiedUuidRoute
  AppOrgAdminsRoute: typeof AppOrgAdminsRoute
  AppOrgAssetCategoriesRoute: typeof AppOrgAssetCategoriesRoute
  AppOrgAssetsRoute: typeof AppOrgAssetsRoute
  AppOrgAttendanceRoute: typeof AppOrgAttendanceRoute
  AppOrgExpenseClaimsRoute: typeof AppOrgExpenseClaimsRoute
  AppOrgHrLettersRoute: typeof AppOrgHrLettersRoute
  AppOrgLeavesRoute: typeof AppOrgLeavesRoute
  AppOrgLetterTemplatesRoute: typeof AppOrgLetterTemplatesRoute
  AppOrgOffboardingRoute: typeof AppOrgOffboardingRoute
  AppOrgPayrollRoute: typeof AppOrgPayrollRoute
  AppOrgSalaryComponentsRoute: typeof AppOrgSalaryComponentsRoute
  AppOrgSupportRoute: typeof AppOrgSupportRouteWithChildren
  AppOrgTeamRoute: typeof AppOrgTeamRouteWithChildren
  AppPaymentCallbackRoute: typeof AppPaymentCallbackRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAttendanceRoute: AppAttendanceRoute,
  AppAutoVerifiedRoute: AppAutoVerifiedRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInboxRoute: AppInboxRoute,
  AppLeavesRoute: AppLeavesRoute,
  AppMyAssetsRoute: AppMyAssetsRoute,
  AppMyExpensesRoute: AppMyExpensesRoute,
  AppMyLettersRoute: AppMyLettersRoute,
  AppMyResignationRoute: AppMyResignationRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppPayrollRoute: AppPayrollRoute,
  AppRequestsRoute: AppRequestsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppAdminActivityLogsRoute: AppAdminActivityLogsRoute,
  AppAdminLeadsRoute: AppAdminLeadsRoute,
  AppAdminLoginHistoryRoute: AppAdminLoginHistoryRoute,
  AppAdminNullRequestsRoute: AppAdminNullRequestsRoute,
  AppAdminOrganizationsRoute: AppAdminOrganizationsRoute,
  AppAdminPaymentsRoute: AppAdminPaymentsRoute,
  AppAdminRequestsRoute: AppAdminRequestsRoute,
  AppAdminSupportRoute: AppAdminSupportRouteWithChildren,
  AppAdminUnresponsiveRoute: AppAdminUnresponsiveRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAutoVerifiedUuidRoute: AppAutoVerifiedUuidRoute,
  AppOrgAdminsRoute: AppOrgAdminsRoute,
  AppOrgAssetCategoriesRoute: AppOrgAssetCategoriesRoute,
  AppOrgAssetsRoute: AppOrgAssetsRoute,
  AppOrgAttendanceRoute: AppOrgAttendanceRoute,
  AppOrgExpenseClaimsRoute: AppOrgExpenseClaimsRoute,
  AppOrgHrLettersRoute: AppOrgHrLettersRoute,
  AppOrgLeavesRoute: AppOrgLeavesRoute,
  AppOrgLetterTemplatesRoute: AppOrgLetterTemplatesRoute,
  AppOrgOffboardingRoute: AppOrgOffboardingRoute,
  AppOrgPayrollRoute: AppOrgPayrollRoute,
  AppOrgSalaryComponentsRoute: AppOrgSalaryComponentsRoute,
  AppOrgSupportRoute: AppOrgSupportRouteWithChildren,
  AppOrgTeamRoute: AppOrgTeamRouteWithChildren,
  AppPaymentCallbackRoute: AppPaymentCallbackRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetPasswordRoute: SetPasswordRoute,
  SystemAdminForgotPasswordRoute: SystemAdminForgotPasswordRoute,
  SystemAdminLoginRoute: SystemAdminLoginRoute,
  SystemAdminResetPasswordRoute: SystemAdminResetPasswordRoute,
  VerifyQrTokenRoute: VerifyQrTokenRoute,
  VerifyLetterQrTokenRoute: VerifyLetterQrTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
